# Generated by Django 4.0.2 on 2022-02-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('srno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('time', models.DateTimeField(blank=True)),
                ('image', models.ImageField(upload_to='media/blog')),
            ],
        ),
    ]
